# Generated by Django 5.1.5 on 2025-03-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fp', '0003_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='title', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
