# Generated by Django 5.1.5 on 2025-03-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fp', '0004_item_title_alter_item_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='genre',
            field=models.IntegerField(choices=[(1, 'Sci-fi'), (2, 'Drama'), (3, 'Comedy')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.IntegerField(choices=[(1, 'Film'), (2, 'Serial'), (3, 'Others')]),
        ),
    ]
