# Generated by Django 5.1.5 on 2025-03-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fp', '0005_alter_item_desc_alter_item_genre_alter_item_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('born', models.DateField()),
            ],
        ),
    ]
