# Generated by Django 5.1.5 on 2025-03-25 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fp', '0006_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='review',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='item_reviews', to='django_fp.review'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='django_fp.item'),
        ),
    ]
