# Generated by Django 5.1.5 on 2025-03-25 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fp', '0007_item_review_alter_review_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='film',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actor_film', to='django_fp.item'),
            preserve_default=False,
        ),
    ]
