# Generated by Django 5.1.5 on 2025-03-25 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fp', '0008_actor_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='actors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='films_actors', to='django_fp.actor'),
            preserve_default=False,
        ),
    ]
