# Generated by Django 5.1.5 on 2025-03-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fp', '0009_item_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actor/'),
        ),
    ]
