# Generated by Django 5.1.5 on 2025-03-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fp', '0010_actor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='actors',
        ),
        migrations.AddField(
            model_name='item',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='films_actors', to='django_fp.actor'),
        ),
    ]
