# Generated by Django 5.1.5 on 2025-03-27 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fp', '0013_remove_item_actors_item_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_reviews', to='django_fp.review'),
        ),
    ]
