# Generated by Django 5.1.5 on 2025-04-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fp', '0016_alter_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='actors',
            field=models.ManyToManyField(related_name='films_actors', to='django_fp.actor'),
        ),
    ]
