# Generated by Django 5.1.5 on 2025-04-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fp', '0017_alter_item_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='films_actors', to='django_fp.actor'),
        ),
    ]
