# Generated by Django 5.1.5 on 2025-04-02 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_fp', '0018_alter_item_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
