# Generated by Django 5.1.5 on 2025-04-02 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_fp', '0020_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
