# Generated by Django 5.1.5 on 2025-04-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fp', '0034_item_average_rating_alter_review_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='film',
        ),
        migrations.AlterField(
            model_name='item',
            name='actors',
            field=models.ManyToManyField(related_name='films', to='django_fp.actor'),
        ),
    ]
