# Generated by Django 5.1.5 on 2025-04-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fp', '0036_item_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
